Change cosign keys
Digital-Ecosystems/ionos-daps pull request #1
Opened 2023-05-10 13:58 UTC by akafazov

2023-05-10 14:50 UTC, akafazov commented
We have to wait Github to resolve Actions partial outage, before triggering the workflow here: https://www.githubstatus.com/

2023-05-11 06:07 UTC, bpavlov-daiteap requested changes

2023-05-11 06:07 UTC, bpavlov-daiteap commented on helm/omejdn-server/values.yaml
> +  repository: ghcr.io/digital-ecosystems/ionos-daps/omejdn-server
repository should be "ghcr.io/digital-ecosystems/omejdn-server" not "ghcr.io/digital-ecosystems/ionos-daps/omejdn-server"

2023-05-11 06:07 UTC, bpavlov-daiteap commented on helm/omejdn-ui/values.yaml
> +  repository: ghcr.io/digital-ecosystems/ionos-daps/omejdn-ui
repository should be "ghcr.io/digital-ecosystems/omejdn-ui" not "ghcr.io/digital-ecosystems/ionos-daps/omejdn-ui"

2023-05-11 06:36 UTC, bpavlov-daiteap approved these changes

2023-05-11 08:52 UTC, bpavlov-daiteap approved these changes

2023-05-11 08:53 UTC, merged